### ISSUE TITLE
Redundant error variables

### ISSUE THREAD

**Issue by laukik-hase** [SRA-VJTI/sra-board-component#17]
https://github.com/SRA-VJTI/sra-board-component/blob/d58505f71440e80b5fe426d02a260f7a3d6b5264/src/adc.c#L8

@ombhilare999 Use a single error variable ```esp_err_t err```for all the purposes. This has already been discussed with @VedantParanjape

**Comment by laukik-hase** [comment]
https://github.com/SRA-VJTI/sra-board-component/blob/1a23093117c9ea1e9f876168f3365ca6997dde12/src/servo.c#L3

@VedantParanjape The error-checking macro is included in every file, can we define it in the helper functions file, so that every component will have direct access to it?

**Comment by VedantParanjape** [comment]
> https://github.com/SRA-VJTI/sra-board-component/blob/1a23093117c9ea1e9f876168f3365ca6997dde12/src/servo.c#L3
> 
> @VedantParanjape The error-checking macro is included in every file, can we define it in the helper functions file, so that every component will have direct access to it?

I wanted the macro to be private, i.e. it shouldn't be accessed by end user, so I preferred putting macro in each source file.

**Comment by laukik-hase** [comment]
> > https://github.com/SRA-VJTI/sra-board-component/blob/1a23093117c9ea1e9f876168f3365ca6997dde12/src/servo.c#L3
> > 
> > @VedantParanjape The error-checking macro is included in every file, can we define it in the helper functions file, so that every component will have direct access to it?
> 
> I wanted the macro to be private, i.e. it shouldn't be accessed by end user, so I preferred putting macro in each source file.

But, if new components are to be added, the user will have to take care of that. Also, it is just a error checking macro, the user cannot do much wrong with it.

**Comment by VedantParanjape** [comment]
> > > https://github.com/SRA-VJTI/sra-board-component/blob/1a23093117c9ea1e9f876168f3365ca6997dde12/src/servo.c#L3
> > > 
> > > @VedantParanjape The error-checking macro is included in every file, can we define it in the helper functions file, so that every component will have direct access to it?
> > 
> > I wanted the macro to be private, i.e. it shouldn't be accessed by end user, so I preferred putting macro in each source file.
> 
> But, if new components are to be added, the user will have to take care of that. Also, it is just a error checking macro, the user cannot do much wrong with it.

Ohk, I'll do it
