### ISSUE TITLE
Specify the exact ESP-IDF version in the README

### ISSUE THREAD

**Issue by laukik-hase** [SRA-VJTI/sra-board-component#44]
Mention the exact version of ESP-IDF that this component uses, which should be the one on which the entire testing phase was completed on.

**Comment by VedantParanjape** [comment]
@SAtacker Please submit a PR with the following changes

**Comment by SAtacker** [comment]
I suppose we are going with 4.1 @VedantParanjape  ?

**Comment by VedantParanjape** [comment]
@SAtacker Nope, we are going to use v4.2-release

**Comment by VedantParanjape** [comment]
Fixed in #45
