### ISSUE TITLE
Description about the component

### ISSUE THREAD

**Issue by laukik-hase** [SRA-VJTI/sra-board-component#46]
@SAtacker Could we also a brief description of what this component does and what it comprises in the README itself?

**Comment by SAtacker** [comment]
Yes, I can update the #45 , will a Table of contents like format be okay or a tabular one ?

**Comment by laukik-hase** [comment]
Yes, that would be nice.

**Comment by VedantParanjape** [comment]
@laukik-hase Please check, it is seems alright, close this issue.
