### ISSUE TITLE
Doxygen autogenerator action doesn't seem to work

### ISSUE THREAD

**Issue by VedantParanjape** [SRA-VJTI/sra-board-component#59]
Checking the gh-pages branch, it doesn't seem like the docs are being pushed to it. Also, it doesn't seem updated on the website.

As of now the website is configured to pull docs from main branch :/docs folder.

**Comment by SAtacker** [comment]
> Checking the gh-pages branch, it doesn't seem like the docs are being pushed to it. Also, it doesn't seem updated on the website.
> 

Can you manually point out any difference between the deployment and the change

**Comment by VedantParanjape** [comment]
> > Checking the gh-pages branch, it doesn't seem like the docs are being pushed to it. Also, it doesn't seem updated on the website.
> 
> Can you manually point out any difference between the deployment and the change

https://sravjti.in/sra-board-component/files.html no oled.h mpu6050.h

**Comment by VedantParanjape** [comment]
> The deployment is active. You can check the logs of workflow. [![Doxygen Action](https://github.com/SRA-VJTI/sra-board-component/actions/workflows/doxy_deploy.yaml/badge.svg)](https://github.com/SRA-VJTI/sra-board-component/actions/workflows/doxy_deploy.yaml)

This doesn't indicate if it does what it is expected to do. For the case, you could just do an echo "hello world" and it will still show action passed.

**Comment by VedantParanjape** [comment]
@SAtacker Check the gh-pages branch as well, it is empty. I think you followed this blog: https://github.com/SRA-VJTI/sra-board-component/blob/main/.github/workflows/doxy_deploy.yaml

Some of the args like deploy branch are missing.

**Comment by SAtacker** [comment]
That's correct. I'll fix it. Seems like :cow: tam's reviews and my PRs are unreliable.

**Comment by VedantParanjape** [comment]
What is this @gautam-dev-maker 🤣

**Comment by SAtacker** [comment]
Also why do we have the https://github.com/SRA-VJTI/sra-board-component/tree/main/docs folder? Should I remove it?
